const TRADE_ARTICLES_WRONG_REQUEST_USER = 'TRADE_ARTICLES_WRONG_REQUEST_USER';
const TRADE_ARTICLES_WRONG_STATE = 'TRADE_ARTICLES_WRONG_STATE';
const TRADE_ARTICLES_BELONG_TO_WRONG_USER = 'TRADE_ARTICLES_BELONG_TO_WRONG_USER';
const TRADE_DELETE_NOT_POSSIBLE = 'TRADE_DELETE_NOT_POSSIBLE';
const TRADE_ACCEPT_DECLINE_NOT_POSSIBLE = 'TRADE_ACCEPT_DECLINE_NOT_POSSIBLE';
const TRADE_SET_DELIVERED_ONLY_POSSIBLE_ON_COMPLETED = 'TRADE_SET_DELIVERED_ONLY_POSSIBLE_ON_COMPLETED';
const TRADE_DOES_NOT_EXIST = 'TRADE_DOES_NOT_EXIST';
const TRADE_ONLY_EDITABLE_BY_TRADE_PARTNER = 'TRADE_ONLY_EDITABLE_BY_TRADE_PARTNER';
const TRADE_STATE_NOT_SUPPORTED = 'TRADE_STATE_NOT_SUPPORTED';
const TRADE_NO_TRADE_PARTNER_FOUND = 'TRADE_NO_TRADE_PARTNER_FOUND';

module.exports = {
    TRADE_ARTICLES_WRONG_REQUEST_USER,
    TRADE_ARTICLES_WRONG_STATE,
    TRADE_ARTICLES_BELONG_TO_WRONG_USER,
    TRADE_DELETE_NOT_POSSIBLE,
    TRADE_ACCEPT_DECLINE_NOT_POSSIBLE,
    TRADE_SET_DELIVERED_ONLY_POSSIBLE_ON_COMPLETED,
    TRADE_DOES_NOT_EXIST,
    TRADE_ONLY_EDITABLE_BY_TRADE_PARTNER,
    TRADE_STATE_NOT_SUPPORTED,
    TRADE_NO_TRADE_PARTNER_FOUND
};
