const TRADE_ACTION_SUBMIT = 'SUBMIT';
const TRADE_ACTION_ACCEPT = 'ACCEPT';
const TRADE_ACTION_DECLINE = 'DECLINE';
const TRADE_ACTION_WITHDRAW = 'WITHDRAW';
const TRADE_ACTION_MAKE_COUNTEROFFER = 'MAKE_COUNTEROFFER';
const TRADE_ACTION_LOAD_USER_ARTICLES = 'LOAD_USER_ARTICLES';
const TRADE_ACTION_LOAD_PARTNER_ARTICLES = 'LOAD_PARTNER_ARTICLES';

export default {
    TRADE_ACTION_SUBMIT,
    TRADE_ACTION_ACCEPT,
    TRADE_ACTION_DECLINE,
    TRADE_ACTION_WITHDRAW,
    TRADE_ACTION_MAKE_COUNTEROFFER,
    TRADE_ACTION_LOAD_USER_ARTICLES,
    TRADE_ACTION_LOAD_PARTNER_ARTICLES
};